project:
  type: website

lang: es

website:
  title: "Feminism Times"
  navbar:
    right:
      - text: "Acerca" 
        href: about.qmd
      - icon: github
        href: https://github.com/Christian-F-Badillo/Class_Proyect_Gender

  page-footer:
      border: true 
      center: "Hecho con [Quarto](https://quarto.org) y 💜 por Ana, America y Christian"
      left:
        - text: "Acerca"
          href: about.qmd
      right: "Género, Feminismo, Violencia y Derechos Humanos"

format:
  html:
    theme: vapor
    css: styles.css
