project:
  type: website

lang: es

website:
  title: "Feminism Times"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: 
      light: pulse
      dark: vapor
    css: styles.css



